
============
Description
============

Outstanding = 0.05 to 0.2
Excellent = 0.2 to 0.4
Great = 0.4 to 0.6
Very Good = 0.6 to 0.8
Good = 0.8 to 0.95
Normal = 0.96 to 1.1
Bad = 1.1 to 1.3
Very bad = 1.3 to 1.6
Awful = 1.6+


============
Burst control
============

=====
Pistols
=====

Compact: 1.3 to 1.5
Carbine: 1.1 to 1.3
Medium: 0.9 to 1.1
Long (or stocked): 0.7 to 0.9

=====
SMG
=====

Unstocked / folded stock:
Compact: 0.5 to 0.7
Carbine: 0.4 to 0.6
Medium: 0.3 to 0.5
Long: 0.2 to 0.35

=====
Shotguns
=====

Unstocked / folded stock:
Compact: 1.2 to 1.5
Carbine: 1 to 1.2
Medium: 0.9 to 1.1
Long: 0.8 to 1

=====
Intermediate Rifles
=====

Unstocked / folded stock:
Compact: 1.05 to 1.2
Carbine: 0.9 to 1.05
Medium: 0.8 to 1
Long: 0.7 to 0.9

=====
Battle Rifles
=====

Unstocked / folded stock:
Compact: 1.65 to 1.9
Carbine: 1.5 to 1.7
Medium: 1.35 to 1.5
Long: 1.15 to 1.3

=====
Machine gun
=====

Unstocked / folded stock:
Compact: 0.26-0.29 | 0.30-0.35
Carbine: 0.30-0.34 | 0.35-0.40
Medium: 0.34-0.39 | 0.40-0.45
Long: 0.40+ | 0.45-0.50


















